version: "3.8"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=Admin@123
      - DB_NAME=ricemart
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: ricemart
    ports:
      - "3306:3306"
